var KEY_ACCESS_TOKEN = "accessToken";

function updateAPIToken(token){
	localStorage.setItem(KEY_ACCESS_TOKEN, token);
}

function getAPIToken(){
	// return 	localStorage.getItem(KEY_ACCESS_TOKEN);
	return 	"Bearer eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJpc3MiOiJodHRwOlwvXC8zLjEwNi4xMzEuMTc5XC9hcGlcL2F1dGhcL2xvZ2luIiwiaWF0IjoxNTk3NzQwMTg2LCJleHAiOjE1OTc4MjY1ODYsIm5iZiI6MTU5Nzc0MDE4NiwianRpIjoiMmlRUDFjWnpoTk4wSzJOciIsInN1YiI6NTksInBydiI6Ijg3ZTBhZjFlZjlmZDE1ODEyZmRlYzk3MTUzYTE0ZTBiMDQ3NTQ2YWEifQ.He9fkFcg1pPcUc_e7N4YDW-Igf7CD-AW88dROil98ZM"
}