var KEY_ACCESS_TOKEN = "accessToken";

function updateAPIToken(token){
	localStorage.setItem(KEY_ACCESS_TOKEN, token);
}

function getAPIToken(){
	// return 	localStorage.getItem(KEY_ACCESS_TOKEN);
	return 	"Bearer eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJpc3MiOiJodHRwOlwvXC8zLjEwNi4xMzEuMTc5XC9hcGlcL2F1dGhcL2xvZ2luIiwiaWF0IjoxNTk3NjQ2MDA2LCJleHAiOjE1OTc3MzI0MDYsIm5iZiI6MTU5NzY0NjAwNiwianRpIjoiZDlraFRaZEJlT1FwWEtLVSIsInN1YiI6NTksInBydiI6Ijg3ZTBhZjFlZjlmZDE1ODEyZmRlYzk3MTUzYTE0ZTBiMDQ3NTQ2YWEifQ.v11v4XS2T6nT5F6E8CxE-MMX12BhRpBxPRX1nrCnxaw";
}